#!/usr/bin/env python3
"""CIT 408 / Assignment 2.1 — capture REAL PostgreSQL evidence.

Run from ~/cit408-coralbay:
    python3 week2/build_fd_proofs.py

Requires the running pg18 container and stage.work_orders_unf already loaded.
Creates/updates week2/fd_checks.sql and week2/fd_results.txt only after
PostgreSQL executes all checks successfully and the evidence is validated.
Never changes stage.work_orders_unf.
"""

from __future__ import annotations

import datetime as dt
import re
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SQL_OUT = HERE / "fd_checks.sql"
RESULTS_OUT = HERE / "fd_results.txt"

SETUP = """-- CIT 408 / Module 2 / Assignment 2.1
-- Functional dependency evidence from the real PostgreSQL stage.work_orders_unf.
-- Generated by build_fd_proofs.py using a single PostgreSQL session.
-- Evidence comments must not be edited to imply a result not observed.
-- The staging table is never updated, preserving the depot-phone conflict.
-- The view excludes empty part-code slots (only populated occurrences remain).
-- There are 2,258 populated lines across 1,100 work orders in this dataset.

CREATE TEMP VIEW fd_part_lines AS
SELECT w.work_order_no, p.part_line_no,
       NULLIF(BTRIM(p.part_code), '') AS part_code,
       NULLIF(BTRIM(p.part_name), '') AS part_name,
       NULLIF(BTRIM(p.part_unit_cost), '') AS part_unit_cost,
       NULLIF(BTRIM(p.part_qty), '') AS part_qty,
       NULLIF(BTRIM(p.supplier_id), '') AS supplier_id,
       NULLIF(BTRIM(p.supplier_name), '') AS supplier_name,
       NULLIF(BTRIM(p.supplier_phone), '') AS supplier_phone
FROM stage.work_orders_unf AS w
CROSS JOIN LATERAL (VALUES
 (1, w.part1_code, w.part1_name, w.part1_unit_cost, w.part1_qty, w.part1_supplier_id, w.part1_supplier_name, w.part1_supplier_phone),
 (2, w.part2_code, w.part2_name, w.part2_unit_cost, w.part2_qty, w.part2_supplier_id, w.part2_supplier_name, w.part2_supplier_phone),
 (3, w.part3_code, w.part3_name, w.part3_unit_cost, w.part3_qty, w.part3_supplier_id, w.part3_supplier_name, w.part3_supplier_phone),
 (4, w.part4_code, w.part4_name, w.part4_unit_cost, w.part4_qty, w.part4_supplier_id, w.part4_supplier_name, w.part4_supplier_phone)
) AS p(part_line_no, part_code, part_name, part_unit_cost, part_qty, supplier_id, supplier_name, supplier_phone)
WHERE NULLIF(BTRIM(p.part_code), '') IS NOT NULL;
"""

# In the single-table 1NF design the PK is (work_order_no, part_line_no).
# FD01-FD07 depend on only the work-order component: partial dependencies.
# FD08-FD17, FD20-FD24 give the intervening determinants in transitive chains.
# FD18-FD19 are intended FULL dependencies; separate minimality tests follow.
FD_SPECS = [
    ("FD01", "work_order_no", "open_date", "stage.work_orders_unf", "partial"),
    ("FD02", "work_order_no", "close_date", "stage.work_orders_unf", "partial"),
    ("FD03", "work_order_no", "truck_id", "stage.work_orders_unf", "partial"),
    ("FD04", "work_order_no", "depot_code", "stage.work_orders_unf", "partial"),
    ("FD05", "work_order_no", "mechanic_id", "stage.work_orders_unf", "partial"),
    ("FD06", "work_order_no", "labor_hours", "stage.work_orders_unf", "partial"),
    ("FD07", "work_order_no", "problem_description", "stage.work_orders_unf", "partial"),
    ("FD08", "truck_id", "truck_vin", "stage.work_orders_unf", "transitive chain"),
    ("FD09", "truck_id", "truck_make", "stage.work_orders_unf", "transitive chain"),
    ("FD10", "truck_id", "truck_model", "stage.work_orders_unf", "transitive chain"),
    ("FD11", "truck_id", "truck_year", "stage.work_orders_unf", "transitive chain"),
    ("FD12", "depot_code", "depot_name", "stage.work_orders_unf", "transitive chain"),
    ("FD13", "depot_code", "depot_city", "stage.work_orders_unf", "transitive chain"),
    ("FD14", "depot_code", "depot_phone", "stage.work_orders_unf", "transitive chain; data conflict"),
    ("FD15", "mechanic_id", "mechanic_name", "stage.work_orders_unf", "transitive chain"),
    ("FD16", "mechanic_id", "mechanic_cert_level", "stage.work_orders_unf", "transitive chain"),
    ("FD17", "mechanic_cert_level", "cert_hourly_rate", "stage.work_orders_unf", "transitive chain"),
    ("FD18", "work_order_no, part_line_no", "part_code", "fd_part_lines", "full; see minimality checks"),
    ("FD19", "work_order_no, part_line_no", "part_qty", "fd_part_lines", "full; see minimality checks"),
    ("FD20", "part_code", "part_name", "fd_part_lines", "transitive chain"),
    ("FD21", "part_code", "part_unit_cost", "fd_part_lines", "transitive chain"),
    ("FD22", "part_code", "supplier_id", "fd_part_lines", "transitive chain"),
    ("FD23", "supplier_id", "supplier_name", "fd_part_lines", "transitive chain"),
    ("FD24", "supplier_id", "supplier_phone", "fd_part_lines", "transitive chain"),
]


def fd_sql(determinant: str, dependent: str, source: str) -> str:
    # TEXT sentinel makes NULL vs non-NULL visible to COUNT(DISTINCT).
    distinct = f"COUNT(DISTINCT COALESCE(NULLIF(BTRIM({dependent}::text), ''), '<NULL>'))"
    return (
        f"SELECT {determinant}, {distinct} AS distinct_values\n"
        f"FROM {source}\n"
        f"GROUP BY {determinant}\n"
        f"HAVING {distinct} > 1;"
    )


# Each CHECK has a label, a SQL statement, and a comment for the reader.
checks: list[tuple[str, str, str]] = []
for label, determinant, dependent, source, classification in FD_SPECS:
    checks.append((label, fd_sql(determinant, dependent, source),
                   f"{determinant} -> {dependent} [{classification}]"))

checks.extend([
    ("KEY_UNIQUENESS", """SELECT work_order_no, part_line_no, COUNT(*) AS occurrences
FROM fd_part_lines
GROUP BY work_order_no, part_line_no
HAVING COUNT(*) > 1;""",
     "A 1NF key cannot repeat."),
    ("KEY_NULLS", """SELECT
  COUNT(*) AS populated_lines,
  COUNT(*) FILTER (WHERE work_order_no IS NULL OR part_line_no IS NULL) AS null_key_components
FROM fd_part_lines;""",
     "Both components of the 1NF composite key must be non-NULL."),
    ("PART_SLOTS", """SELECT part_line_no, COUNT(*) AS populated_lines
FROM fd_part_lines
GROUP BY part_line_no
ORDER BY part_line_no;""",
     "Confirms only numbered slots 1-4 are used; totals should sum to 2,258."),
    ("DEPOT_PHONE_COUNTS", """SELECT depot_code, depot_phone, COUNT(*) AS work_order_count
FROM stage.work_orders_unf
WHERE depot_code = 'DEP-FLL'
GROUP BY depot_code, depot_phone
ORDER BY depot_phone;""",
     "Frequency evidence supporting a PROVISIONAL canonical-phone rule."),
    ("DEPOT_AFFECTED", """SELECT work_order_no, depot_code, depot_phone
FROM stage.work_orders_unf
WHERE depot_code = 'DEP-FLL' AND depot_phone = '(954) 555-0181'
ORDER BY work_order_no;""",
     "Lists anomalous work orders; verify the phone against the depot master record."),
    ("QTY_BY_ORDER", """SELECT work_order_no, COUNT(DISTINCT part_qty) AS quantity_variants
FROM fd_part_lines
GROUP BY work_order_no
HAVING COUNT(DISTINCT part_qty) > 1
ORDER BY work_order_no LIMIT 10;""",
     "Counterexamples to work_order_no alone determining part_qty (FD19 minimality)."),
    ("QTY_BY_SLOT", """SELECT part_line_no, COUNT(DISTINCT part_qty) AS quantity_variants
FROM fd_part_lines
GROUP BY part_line_no
HAVING COUNT(DISTINCT part_qty) > 1
ORDER BY part_line_no;""",
     "Counterexamples to part_line_no alone determining part_qty (FD19 minimality)."),
    ("CODE_BY_ORDER", """SELECT work_order_no, COUNT(DISTINCT part_code) AS part_variants
FROM fd_part_lines
GROUP BY work_order_no
HAVING COUNT(DISTINCT part_code) > 1
ORDER BY work_order_no LIMIT 10;""",
     "Counterexamples to work_order_no alone determining part_code (FD18 minimality)."),
    ("CODE_BY_SLOT", """SELECT part_line_no, COUNT(DISTINCT part_code) AS part_variants
FROM fd_part_lines
GROUP BY part_line_no
HAVING COUNT(DISTINCT part_code) > 1
ORDER BY part_line_no;""",
     "Counterexamples to part_line_no alone determining part_code (FD18 minimality)."),
    ("TRUCK_DEPOT", """SELECT truck_id, COUNT(DISTINCT depot_code) AS depots
FROM stage.work_orders_unf
GROUP BY truck_id
HAVING COUNT(DISTINCT depot_code) > 1
ORDER BY truck_id;""",
     "If rows appear, truck_id does not determine depot_code; depot belongs on WORK_ORDER."),
])

# These checks are specific to the assignment's known 1,100-row dataset.
# Any unexpected result should STOP finalization rather than be hidden.
EXPECTED_ROWS = {**{f"FD{i:02d}": (1 if i == 14 else 0) for i in range(1, 25)},
                 "KEY_UNIQUENESS": 0, "KEY_NULLS": 1, "PART_SLOTS": 4,
                 "DEPOT_PHONE_COUNTS": 2, "DEPOT_AFFECTED": 2,
                 "QTY_BY_ORDER": 10, "QTY_BY_SLOT": 4,
                 "CODE_BY_ORDER": 10, "CODE_BY_SLOT": 4,
                 "TRUCK_DEPOT": 40}


def extract_captured_output(stdout: str) -> dict[str, str]:
    lines = stdout.splitlines()
    captures: dict[str, str] = {}
    current: str | None = None
    buffer: list[str] = []
    for line in lines:
        if line.startswith("__BEGIN_FD_EVIDENCE_") and line.endswith("__"):
            if current is not None:
                raise ValueError(f"Nested evidence marker: {current}")
            current = line[len("__BEGIN_FD_EVIDENCE_"):-2]
            buffer = []
        elif line.startswith("__END_FD_EVIDENCE_") and line.endswith("__"):
            label = line[len("__END_FD_EVIDENCE_"):-2]
            if current != label:
                raise ValueError(f"Mismatched evidence marker: {label} != {current}")
            captures[label] = "\n".join(buffer).strip("\n")
            current, buffer = None, []
        elif current is not None:
            buffer.append(line)
    if current is not None:
        raise ValueError(f"Unclosed evidence marker for {current}")
    return captures


def nrows(output: str) -> int:
    found = re.findall(r"^\((\d+) rows?\)$", output, re.MULTILINE)
    if len(found) != 1:
        raise ValueError(f"Cannot identify PostgreSQL row-count footer: {output[-400:]!r}")
    return int(found[0])


def main() -> int:
    if len(checks) != 34:
        raise RuntimeError(f"Unexpected number of check blocks: {len(checks)}")
    psql_input = SETUP + "\n"
    for label, sql, _description in checks:
        psql_input += f"\n\\echo __BEGIN_FD_EVIDENCE_{label}__\n{sql}\n\\echo __END_FD_EVIDENCE_{label}__\n"
    cmd = ["sudo", "-n", "docker", "exec", "-i", "pg18", "psql", "-X", "-P", "pager=off",
           "-v", "ON_ERROR_STOP=1", "-U", "postgres", "-d", "coralbay"]
    print("Executing 24 FD checks and 10 supporting checks against PostgreSQL...")
    try:
        run = subprocess.run(cmd, input=psql_input, text=True, capture_output=True, check=False)
    except FileNotFoundError as exc:
        print(f"ERROR: required executable not available: {exc}", file=sys.stderr)
        return 1
    if run.returncode != 0:
        print("PostgreSQL failed; no submission files were changed.", file=sys.stderr)
        print(run.stderr[-3000:], file=sys.stderr)
        return 1
    captured = extract_captured_output(run.stdout)
    if set(captured) != {x[0] for x in checks}:
        print("Incomplete evidence markers; no files were changed.", file=sys.stderr)
        return 1
    for label, expected in EXPECTED_ROWS.items():
        found = nrows(captured[label])
        if found != expected:
            print(f"UNEXPECTED RESULT for {label}: {found} rows, expected {expected}. No files were changed.", file=sys.stderr)
            return 1
    for label, snippets in {
        "FD14": ["DEP-FLL", "2"],
        "DEPOT_PHONE_COUNTS": ["(954) 555-0118", "266", "(954) 555-0181", "2"],
        "DEPOT_AFFECTED": ["WO-50041", "WO-50047"],
        "PART_SLOTS": ["1100", "714", "330", "114"],
    }.items():
        if not all(s in captured[label] for s in snippets):
            print(f"UNEXPECTED VALUES for {label}. No files were changed.", file=sys.stderr)
            return 1
    if " 2258 " not in " " + captured["KEY_NULLS"].replace("|", " ") + " ":
        # psql pretty printed whitespace can vary; use token-boundary checks.
        if not re.search(r"\b2258\b", captured["KEY_NULLS"]):
            print("Expected 2,258 populated part lines; no files were changed.", file=sys.stderr)
            return 1
    if not re.search(r"\b0\b", captured["KEY_NULLS"]):
        print("Expected no NULL key components; no files were changed.", file=sys.stderr)
        return 1

    now = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    intro = SETUP.replace(
        "-- Generated by build_fd_proofs.py using a single PostgreSQL session.",
        "-- PostgreSQL results captured by build_fd_proofs.py on " + now + "."
    )
    out = [intro]
    raw = [f"CIT 408 - PostgreSQL FD checks captured {now}",
           "Server container: pg18; database: coralbay; staging table unchanged", ""]
    out.append("""-- ================================================================
-- 2NF explanation: FD01-FD07 describe work-order-header attributes
-- determined by work_order_no alone, not the 1NF composite key.
-- Moving them to WORK_ORDER_2NF (single-column PK work_order_no)
-- eliminates these partial dependencies; part rows retain their
-- composite PK (work_order_no, part_line_no).
-- ================================================================
-- 3NF explanation: FD08-FD17 and FD20-FD24 are the intermediate
-- determinants in transitive dependency chains relative to the 1NF
-- key. TRUCK, DEPOT, CERTIFICATION, MECHANIC, PART and SUPPLIER
-- separate these attributes. WORK_ORDER keeps depot_code as an FK:
-- a truck can be serviced at more than one depot.
-- ================================================================
""")
    sections = {"FD01": "-- === Functional dependency proof queries: FD01-FD24 ===",
                "KEY_UNIQUENESS": "-- === 1NF key and populated part slot checks ===",
                "DEPOT_PHONE_COUNTS": "-- === Depot telephone conflict and resolution rule ===",
                "QTY_BY_ORDER": "-- === FULL-dependency minimality counterexamples ===",
                "TRUCK_DEPOT": "-- === Negative test: truck_id does NOT determine depot_code ==="}
    for label, sql, meaning in checks:
        if label in sections:
            out.append(sections[label] + "\n")
        out.append(f"-- {label}: {meaning}\n{sql}")
        raw.append(f"==== {label}: {meaning} ====")
        raw.append(captured[label])
        raw.append("")
        out.append(f"-- Actual PostgreSQL output ({label}; {now}):")
        out += ["-- " + line for line in captured[label].splitlines()]
        if label == "DEPOT_AFFECTED":
            out.append("""-- Resolution policy: The 266-record value (954) 555-0118 is the
-- PROVISIONAL canonical DEP-FLL phone, not independently established
-- as the official number. Flag WO-50041 and WO-50047 (0181) for
-- maintenance-team verification against the official depot contact
-- record. Preserve the raw staging data without alteration. After
-- verification, DEPOT will store exactly one confirmed phone per code.""")
        if label in ("QTY_BY_SLOT", "CODE_BY_SLOT"):
            out.append("-- Interpretation: Multiple distinct values for each slot number")
            out.append("-- mean the slot alone is not a determinant.")
        if label in ("QTY_BY_ORDER", "CODE_BY_ORDER"):
            out.append("-- Interpretation: Listed counterexamples show work_order_no")
            out.append("-- alone does not determine the value on all part lines.")
        if label == "TRUCK_DEPOT":
            out.append("-- Interpretation: Nonzero results disprove truck_id -> depot_code.")
            out.append("-- Keep depot_code on WORK_ORDER, not permanently on TRUCK.")
        out.append("")
    # Atomically update only after evidence is captured and validated.
    tmp_sql = SQL_OUT.with_suffix(".sql.tmp")
    tmp_raw = RESULTS_OUT.with_suffix(".txt.tmp")
    tmp_sql.write_text("\n".join(out) + "\n", encoding="utf-8")
    tmp_raw.write_text("\n".join(raw) + "\n", encoding="utf-8")
    tmp_sql.replace(SQL_OUT)
    tmp_raw.replace(RESULTS_OUT)
    print(f"SUCCESS: verified {len(checks)} PostgreSQL check outputs.")
    print(f"Updated {SQL_OUT.name} with actual psql results below each query.")
    print(f"Saved labeled raw results in {RESULTS_OUT.name}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
